map:                                            #Configuration regarding the map
    - top_map: assets/maps/school.csv           #Highest level of the map
    - other_maps: assets/maps                   #All other maps, needs to be a directory, which can contain top_map
data:                                           #Configuration regarding the school data
    - data_type: CSV                            #The type of data stored in the data files
    - staff_location: assets/staff.csv          #The location of the staff data
    - subjects_location: assets/subjects.csv    #The location of the subject data
    - classes_location: assets/classes.csv      #The location of the class data
data_source:                                    #Configuration regarding the data source
    - type: MARIADB                             #The type of data source. The other entries are dependent on this type value
    - addr: 127.0.0.1                           #The address of the database server
    - database: school                          #The name of the database